### ISSUE TITLE
bang ga bisa api nya

### ISSUE THREAD

**Issue by bobwatcherx** [kodingkeun/teradood#3]
ane eror sepert ini 
root@boo-HP-Convertible-x360-11-ab1XX:/home/boo# curl -X POST -H "Content-Type: application/x-www-form-urlencoded; charset=UTF-8" -d "pesan=API+INI+BEBAS+DIPAKAI&url=https://ds2play.com/d/ywjexvglwx0l" https://api.hunternblz.com/doodstream
curl: (6) Could not resolve host: api.hunternblz.com
root@boo-HP-Convertible-x360-11-ab1XX:/home/boo# 

bisa di update lagi project nya

**Comment by ibnusyawall** [comment]
udah mokad api nya bang
